### ISSUE TITLE
Error: Markdown() takes 1 positional argument but 2 where given

### ISSUE THREAD

**Issue by BorisLS** [tylerFowler/docker-superset#13]
Hey Tyler, thanks for yor work on the Docker Image for Superset! I just wanted to try it but I got an error. Do you have any idea what goes wrong here?

`
docker-superset bluetke$ docker run --name superset -p 8088:8088 tylerfowler/superset
`

Checking for existing Superset config...
No Superset config found, creating from environment
Checking for docker-entrypoint
Running first time setup for Superset
Creating admin user admin
Username [admin]: User first name [admin]: User last name [user]: Email [admin@fab.org]: Password: Repeat for confirmation: Loaded your LOCAL configuration at [/superset/superset_config.py]
Was unable to import superset Error: markdown() takes 1 positional argument but 2 were given
/usr/local/lib/python3.6/getpass.py:91: GetPassWarning: Can not control echo on the terminal.
  passwd = fallback_getpass(prompt, stream)
Warning: Password input may be echoed.

Warning: Password input may be echoed.

/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)

**Comment by tylerFowler** [comment]
Ah, ok, this version has the following issues:
https://github.com/apache/incubator-superset/issues/5958
https://github.com/apache/incubator-superset/issues/4953

I've repushed version `0.27.0` with manual fixes for these issues. But please let me know if you still run into them.

**Comment by BorisLS** [comment]
thank you - container is running 👍
