### ISSUE TITLE
Add cx_oracle but can not see the pages

### ISSUE THREAD

**Issue by Saber0517** [tylerFowler/docker-superset#3]
Hi tyler I try to add cx_oracle base on your images,but I can no see the pages after I run it.
Could you please kindly review and told me what I done wrong？

`FROM tylerfowler/superset

ENV ORACLE_HOME /opt/oracle/instantclient_12_1
ENV LD_RUN_PATH=$ORACLE_HOME

COPY instantclient/* /tmp/

RUN apt-get update \
&& apt-get install -y \
     unzip \ 
     libaio-dev

RUN \
	mkdir -p /opt/oracle && \
	unzip "/tmp/instantclient*.zip" -d /opt/oracle && \
	ln -s $ORACLE_HOME/libclntsh.so.12.1 $ORACLE_HOME/libclntsh.so

RUN pip install cx_Oracle`

**Comment by tylerFowler** [comment]
Were you able to solve this? I don't have much experience with oracle but I can try and help troubleshooting.

**Comment by Saber0517** [comment]
Hi, tylerFlowler, I am able to connect oracle now(It turns out that it just too slow.... need to make some time to boot up), but it seems like the oracle won't work well in SQL lab. 

[https://github.com/airbnb/superset/issues/2534](https://github.com/airbnb/superset/issues/2534)

I  think it is a known issue and still not have any solution, anyway thanks for your docker file build. I will make a pull request to you if you like to support Oracle connect after they solve the issues.
