### ISSUE TITLE
No module named MySQLdb

### ISSUE THREAD

**Issue by EderO** [tylerFowler/docker-superset#5]
Error while adding Mysql database.

**Comment by tylerFowler** [comment]
So currently the only database driver installed on the image by default is the PostgreSQL driver (to keep the image size small), you'll have to make an image on top of this one that installs the driver you need.

If you are doing this though and still seeing an issue let me know and I can look into it.

**Comment by tylerFowler** [comment]
Closing now, assuming the error was caused by the reasons above
